homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitudesecret
  longitude: !secret longitudesecret
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevationsecret
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # UI Customizations
  customize: !include customizations.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

logger:
  default: warn

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

# Media Player Components
media_player: !include media_players.yaml

# Ecobee4 Thermostat
ecobee:
  api_key: !secret ecobeeapikey

# Z-Wave
zwave:
  usb_path: /dev/ttyACM0
  new_entity_ids: true
  network_key: !secret zwavenetworkkey

# Amazon Echo Emulated Hue
emulated_hue:
  listen_port: 80
  off_maps_to_on_domains:
  exposed_domains:
    - switch
    - light
    - group
    - input_boolean

# Sensor Components
sensor: !include sensors.yaml

input_boolean: !include input_booleans.yaml
input_select: !include input_selects.yaml
script: !include scripts.yaml
group: !include groups.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
