# Weather Tracking
- platform: wunderground
  api_key: !secret wundergroundkey
  monitored_conditions:
    - weather_1d
#    - temp_high_1d_f
    - temp_f
#    - temp_low_1d_f
    - relative_humidity
    - precip_1d
    - precip_1d_in
    - wind_mph
    - wind_1d_mph
    - alerts

# Plex Server Sensor
- platform: plex
  host: 192.168.150.12
  username: !secret plexuser
  password: !secret plexpw

# Ohm Connect - Power Demand Cycling
- platform: ohmconnect
  id: !secret ohmconnectkey

# Custom Sensors
- platform: template
  sensors:
    # Idle Living Room TV
    living_room_tv_idle:
      friendly_name: 'Living Room TV is Idle'
      value_template: >-
        {% if (is_state_attr('media_player.pioneer_avr', 'source', 'Chromecast') and is_state('media_player.living_room_chromecast', 'off')) %}
          on
        {% else %}
          off
        {% endif %}
      entity_id:
        - media_player.pioneer_avr
        - media_player.living_room_chromecast

    living_room_tv_volume:
      friendly_name: 'Living Room TV Volume'
      unit_of_measurement: 'dB'
      value_template: >-
        {% if is_state('media_player.pioneer_avr', 'on') %}
          {% set n = states.media_player.pioneer_avr.attributes.volume_level|float %}
          {{ (n*92.5-80.5)|round(0.0) }}
        {% else %}
          -80.5
        {% endif %}

    # Battery Status
    front_door_battery:
      friendly_name: 'Front Door Battery Level'
      value_template: >-
        {%- if states.zwave.front_door -%}
          {{ states.zwave.front_door.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      entity_id: zwave.front_door

    front_gate_battery:
      friendly_name: 'Front Gate Battery Level'
      value_template: >-
        {%- if states.zwave.front_gate -%}
          {{ states.zwave.front_gate.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      entity_id: zwave.front_gate

    back_door_battery:
      friendly_name: 'Back Door Battery Level'
      value_template: >-
        {%- if states.zwave.back_door -%}
          {{ states.zwave.back_door.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      entity_id: zwave.back_door

    garage_door_battery:
      friendly_name: 'Garage Door Battery Level'
      value_template: >-
        {%- if states.zwave.garage_door -%}
          {{ states.zwave.garage_door.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      entity_id: zwave.garage_door

    living_room_smoke_battery:
      friendly_name: 'Living Room Smoke Detector Battery Level'
      value_template: >-
        {%- if states.zwave.living_room_smoke_detector -%}
          {{ states.zwave.living_room_smoke_detector.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      entity_id: zwave.living_room_smoke_detector

    # First Alert ZCOMBO-G Smoke Detector
    living_room_smoke:
      friendly_name: 'Living Room Smoke Detector Status'
      value_template: >-
        {%- if is_state("sensor.living_room_smoke_detector_alarm_level", "0") %}
          Idle
        {%- else %}
          {%- if is_state("sensor.living_room_smoke_detector_alarm_type", "1") %}
            Fire
          {%- elif is_state("sensor.living_room_smoke_detector_alarm_type", "2") %}
            C02
          {%- elif is_state("sensor.living_room_smoke_detector_alarm_type", "12") %}
            Testing
          {%- elif is_state("sensor.living_room_smoke_detector_alarm_type", "13") %}
            Idle
          {% else %}
            Unknown
          {%- endif %}
        {%- endif %}
      entity_id: zwave.living_room_smoke_detector
